apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bl-eks-dev-cluster-02
  region: us-gov-west-1

vpc:
  subnets:
    private:
      us-gov-west-1a: { id: subnet-0c1dfa2228fa0b6f9 }
      us-gov-west-1b: { id: subnet-073c5f4e89a529c18 }
    public:
      us-gov-west-1a: { id: subnet-0c4d30ac3c00b32f6 }
      us-gov-west-1b: { id: subnet-0010257a869fc397b }

managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    minSize: 3
    maxSize: 6
    desiredCapacity: 5
    volumeSize: 20
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    iam:
      withAddonPolicies:
        autoScaler: true
